#!/bin/bash

#!/bin/bash

## 서비스 목록 정의
services=("order-service" "catalog-service" "config-service" "dispatcher-service" "edge-service")

# 루프를 통해 각 서비스의 이미지를 로컬에서 빌드
for service in "${services[@]}"; do
  echo "=== Building Docker image for $service ==="

#  # 서비스 디렉터리로 이동
#  cd $service || exit

  # Gradle 빌드를 통해 JAR 파일 생성 (필요시)
#  ./gradlew clean
  ./gradlew :$service:build -x test
  ./gradlew :$service:bootJar -x test


done


## 루프를 통해 각 서비스의 이미지를 로컬에서 빌드
for service in "${services[@]}"; do
  echo "=== Building Docker image for $service ==="

  pwd

  # Docker 이미지 빌드 (서비스 이름을 태그로 사용)
  docker build -t "$service:latest" -f "$service/Dockerfile" "$service"


  echo "=== Docker image for $service built successfully ==="
done

echo "All Docker images have been built locally."
