services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  stastd:
    image: prom/statsd-exporter:master
    container_name: statsd
    command: '--statsd.event-flush-threshold=1 --log.level=debug'
    ports:
      - 9125:9125/udp
      - 9102:9102
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./infra-config/prometheus/:/etc/prometheus/"      
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'      
    expose:
      - 9090
    ports:
      - 9090:9090
