version: '3.3'  # 파일 규격 버전
services:       # 이 항목 밑에 실행하려는 컨테이너 들을 정의
  prometheus:
    image: prom/prometheus
    container_name: book-prom
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/volume:/prometheus
    ports:
      - "9090:9090" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    command: # web.enalbe-lifecycle은 api 재시작없이 설정파일들을 reload 할 수 있게 해줌
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    networks:
      - promnet

#  grafana:
#    image: grafana/grafana
#    container_name: book-prom
#    # user: "$GRA_UID:$GRA_GID"
#    ports:
#      - "3000:3000" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
#    volumes:
#      - ./grafana/volume:/var/lib/grafana
#      - ./grafana/provisioning/:/etc/grafana/provisioning/
#    restart: always
#    networks:
#      - promnet
#    depends_on:
#      - prometheus

networks:
  promnet:
    driver: bridge