version: "3"

services:
  sr4-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  sr4-social:
    image: sr4/social
    ports:
      - 8080:8080
      - 5005:5005
    links:
      - sr4-postgres
