# This is the app definition for running in dev.
# It uses a Sqlit database inside the web app container.
version: "3.7"

services:
  todo-web:
    image: diamol/ch06-todo-list
    ports:
      - "8020:80"
    environment:
      - Database:Provider=Sqlite
    networks:
      - app-net

networks:
  app-net:
    external:
      name: nat
