services:
  pkgserver:
    image: practicalgo/pkgserver
    environment:
      - LOG_LEVEL=0
      - JAEGER_ADDR=http://jaeger:14268
      - STATSD_ADDR=statsd:9125
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      - BUCKET_NAME=test-bucket
      - S3_ADDR=minio:9000
      - DB_ADDR=mysql:3306
      - DB_NAME=package_server
      - DB_USER=packages_rw
      - DB_PASSWORD=password
      - USERS_SVC_ADDR=users-svc:50051
  users-svc:
    image: practicalgo/users-svc
    environment:
      - LOG_LEVEL=0
      - JAEGER_ADDR=http://jaeger:14268
      - STATSD_ADDR=statsd:9125
  mysql:
    image: mysql:8.0.26
    environment:    
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=package_server
      - MYSQL_USER=packages_rw
      - MYSQL_PASSWORD=password
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./http-server/mysql-init:/docker-entrypoint-initdb.d
  minio:
    image: minio/minio:RELEASE.2021-07-08T01-15-01Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    ports:
      - 9000:9000
      - 9001:9001
    command: 'server "/data" --console-address ":9001"'        
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
  stastd:
    image: prom/statsd-exporter:master
    container_name: statsd
    command: '--statsd.event-flush-threshold=1'
    ports:
      - 9125:9125/udp
      - 9102:9102
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "./infra-config/prometheus/:/etc/prometheus/"      
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'      
    expose:
      - 9090
    ports:
      - 9090:9090  
