version: "3.7"

x-args: &args
  args:
    BUILD_NUMBER: ${BUILD_NUMBER:-0}
    BUILD_TAG: ${BUILD_TAG:-local}

services:
  timecheck:
    build:
      context: timecheck
      dockerfile: Dockerfile-3.0
      <<: *args
