apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.11.3/manifests/install.yaml

patches:
  - path: patch-service.yml
