version: "3.7"

services:
  numbers-api:
    healthcheck:
      test: ["CMD", "dotnet", "Utilities.HttpCheck.dll", "-u", "http://localhost/health", "-t", "500"]
      interval: 2s
      timeout: 3s
      retries: 2
      start_period: 5s

  numbers-web:
    healthcheck:
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s
