version: "3.7"

services:
  numbers-api:
    deploy:
      replicas: 6
      resources:
        limits:
          cpus: "0.50"
          memory: 75M

  numbers-web:
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.75"
          memory: 150M

networks:
  app-net:
    name: numbers-prod
