version: "3.7"

services:
  todo-web:
    image: diamol/ch21-todo-list
    ports:
      - 8080:80
    networks:
      - app-net

  todo-db:
    image: diamol/postgres:11.5
    networks:
      - app-net

  message-queue:
    image: diamol/nats
    ports:
      - "8222:8222"
    networks:
      - app-net

  save-handler:
    image: diamol/ch21-save-handler
    environment:
      - Events__events.todo.itemsaved__Publish=true
    networks:
      - app-net

  todo-api:
    image: diamol/ch21-todo-api
    ports:
      - 8081:80
    networks:
      - app-net

  audit-handler:
    image: diamol/ch21-audit-handler
    networks:
      - app-net

  mutating-handler:
    image: diamol/ch21-mutating-handler
    environment:
      - MessageQueue__Url=nats://message-queue:4222
    networks:
      - app-net

networks:
  app-net:
