tempo:
  repository: "grafana/tempo"
  tag: 2.5.0

  reportingEnabled: false

  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus/api/v1/write"

  retention: 1h

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"
    zipkin:
      endpoint: "0.0.0.0:9411"
    
  persistence:
    enabled: true
